name: "build and deploy"
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    if: github.actor != 'depbot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'
          cache: 'pnpm'

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
          architecture: "x64"

      - name: Build
        run: |
          pnpm install
          pnpm build
          python3 -m pip install -r requirements.txt
          python3 ./python_scripts/compress_by_brotli.py
          python3 ./python_scripts/compress_by_gzip.py
          python3 ./python_scripts/convert_img2webp.py
          tar -zcvf release.tgr.gz ./public/

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "release.tgr.gz"
          target: "/tmp"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd redlnn.top
            tar -xzvf /tmp/release.tgr.gz
            rm -rf /tmp/release.tgr.gz
            ./backup.sh hexo
            mv public hexo
